### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by puks** [johndavedecano/paymongo-nodejs#5]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

npm install gives off this error

> node -e "if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('paymongo-nodejs must be installed with Yarn: https://yarnpkg.com/')"

[eval]:1
if(process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('paymongo-nodejs must be installed with Yarn: https://yarnpkg.com/')
                                                    ^

Error: paymongo-nodejs must be installed with Yarn: https://yarnpkg.com/
    at [eval]:1:59
    at Script.runInThisContext (vm.js:116:20)
    at Object.runInThisContext (vm.js:306:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3

thanks!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by davepropelio** [comment]
thanks
